import express from 'express';import cors from 'cors';import crypto from 'crypto';import jwt from 'jsonwebtoken';import bcrypt from 'bcryptjs';import 'dotenv/config';import {pool} from './db.js';
const app=express(),port=Number(process.env.PORT||3000);app.use(cors({origin:process.env.CORS_ORIGIN||'http://localhost:5173'}));app.use(express.json());
const norm=p=>(p||'').replace(/\D/g,'');const sign=p=>jwt.sign(p,process.env.JWT_SECRET,{expiresIn:'7d'});
function auth(req,res,next){const h=req.headers.authorization||'';try{req.auth=jwt.verify(h.startsWith('Bearer ')?h.slice(7):'',process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'Sesión no válida'})}}
app.get('/api/health',async(_,res)=>{try{await pool.query('SELECT 1');res.json({ok:true})}catch{res.status(500).json({ok:false})}});
app.get('/api/campaigns',async(_,res)=>{const[r]=await pool.query('SELECT id,name,slug,campaign_type,edition_number,description,start_date,end_date FROM campaigns WHERE active=TRUE ORDER BY id DESC');res.json(r)});
app.post('/api/users/register',async(req,res)=>{const name=String(req.body.name||'').trim(),phone=norm(req.body.phone);if(!name||phone.length<9)return res.status(400).json({error:'Nombre y móvil válidos son obligatorios'});const[e]=await pool.query('SELECT id,name,phone,phone_verified FROM users WHERE phone_normalized=?',[phone]);if(e.length){const u=e[0];return res.json({user:u,token:sign({role:'customer',userId:u.id})})}const[r]=await pool.query('INSERT INTO users(name,phone,phone_normalized) VALUES(?,?,?)',[name,phone,phone]);const u={id:r.insertId,name,phone,phone_verified:false};res.status(201).json({user:u,token:sign({role:'customer',userId:u.id})})});
app.get('/api/campaigns/:id/summary',auth,async(req,res)=>{if(req.auth.role!=='customer')return res.sendStatus(403);const id=Number(req.params.id),uid=req.auth.userId;const[[c]]=await pool.query('SELECT id,name,first_visit_points,repeat_visit_points FROM campaigns WHERE id=? AND active=TRUE',[id]);if(!c)return res.sendStatus(404);const[[t]]=await pool.query('SELECT COALESCE(SUM(points),0) points,COUNT(*) participations FROM participations WHERE campaign_id=? AND user_id=?',[id,uid]);const[e]=await pool.query('SELECT e.id,e.name,e.address,COUNT(v.id) visits FROM campaign_establishments ce JOIN establishments e ON e.id=ce.establishment_id LEFT JOIN visits v ON v.campaign_id=ce.campaign_id AND v.establishment_id=ce.establishment_id AND v.user_id=? WHERE ce.campaign_id=? AND ce.active=TRUE GROUP BY e.id,e.name,e.address,ce.display_order ORDER BY ce.display_order',[uid,id]);res.json({campaign:c,totals:t,establishments:e})});
app.post('/api/campaigns/:id/qr',auth,async(req,res)=>{if(req.auth.role!=='customer')return res.sendStatus(403);const id=Number(req.params.id),uid=req.auth.userId;const[e]=await pool.query('SELECT id,qr_token FROM participant_qrs WHERE user_id=? AND campaign_id=? AND active=TRUE',[uid,id]);if(e.length)return res.json(e[0]);const token=crypto.randomBytes(32).toString('hex');const[r]=await pool.query('INSERT INTO participant_qrs(user_id,campaign_id,qr_token) VALUES(?,?,?)',[uid,id,token]);res.status(201).json({id:r.insertId,qr_token:token})});
app.post('/api/staff/login',async(req,res)=>{const id=Number(req.body.staffId);if(id!==1||req.body.password!=='demo')return res.status(401).json({error:'Credenciales de demo: empleado 1 / demo'});res.json({token:sign({role:'staff',staffId:1,establishmentId:1}),staff:{id:1,name:'Personal de prueba',establishmentId:1}})});
app.post('/api/visits/validate',auth,async(req,res)=>{if(req.auth.role!=='staff')return res.sendStatus(403);const token=String(req.body.qrToken||'').trim();const con=await pool.getConnection();try{await con.beginTransaction();const[q]=await con.query('SELECT pq.user_id,pq.campaign_id,c.first_visit_points,c.repeat_visit_points,c.name campaign_name FROM participant_qrs pq JOIN campaigns c ON c.id=pq.campaign_id WHERE pq.qr_token=? AND pq.active=TRUE AND c.active=TRUE',[token]);if(!q.length){await con.rollback();return res.status(404).json({error:'QR no válido'})}const x=q[0];const[p]=await con.query('SELECT 1 FROM campaign_establishments WHERE campaign_id=? AND establishment_id=? AND active=TRUE',[x.campaign_id,req.auth.establishmentId]);if(!p.length){await con.rollback();return res.status(400).json({error:'El establecimiento no participa en esta campaña'})}const[v]=await con.query('SELECT COUNT(*) total FROM visits WHERE campaign_id=? AND user_id=? AND establishment_id=?',[x.campaign_id,x.user_id,req.auth.establishmentId]);const n=Number(v[0].total)+1,points=n===1?x.first_visit_points:x.repeat_visit_points,reason=n===1?'FIRST_VISIT':'REPEAT_VISIT';const[vr]=await con.query('INSERT INTO visits(campaign_id,user_id,establishment_id,staff_user_id,visit_number_at_establishment,participation_points) VALUES(?,?,?,?,?,?)',[x.campaign_id,x.user_id,req.auth.establishmentId,req.auth.staffId,n,points]);await con.query('INSERT INTO participations(campaign_id,user_id,visit_id,points,reason) VALUES(?,?,?,?,?)',[x.campaign_id,x.user_id,vr.insertId,points,reason]);await con.commit();const[[u]]=await pool.query('SELECT name FROM users WHERE id=?',[x.user_id]);res.status(201).json({success:true,customerName:u.name,points,visitNumber:n,campaignName:x.campaign_name})}catch(e){await con.rollback();console.error(e);res.status(500).json({error:'No se pudo validar la visita'})}finally{con.release()}});

const requireAdmin=(req,res,next)=>req.auth?.role==='admin'?next():res.status(403).json({error:'Permisos insuficientes'});
app.post('/api/admin/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!email||!password)return res.status(400).json({error:'Email y contraseña son obligatorios'});const[r]=await pool.query('SELECT id,name,email,password_hash FROM admin_users WHERE email=? AND active=TRUE LIMIT 1',[email]);if(!r.length)return res.status(401).json({error:'Credenciales incorrectas'});const a=r[0];if(!await bcrypt.compare(password,a.password_hash))return res.status(401).json({error:'Credenciales incorrectas'});res.json({token:sign({role:'admin',adminId:a.id}),admin:{id:a.id,name:a.name,email:a.email}})});
app.get('/api/admin/dashboard',auth,requireAdmin,async(_,res)=>{const[[campaigns]]=await pool.query('SELECT COUNT(*) total FROM campaigns');const[[activeCampaigns]]=await pool.query('SELECT COUNT(*) total FROM campaigns WHERE active=TRUE');const[[users]]=await pool.query('SELECT COUNT(*) total FROM users');const[[establishments]]=await pool.query('SELECT COUNT(*) total FROM establishments WHERE active=TRUE');const[[visits]]=await pool.query('SELECT COUNT(*) total FROM visits');const[[points]]=await pool.query('SELECT COALESCE(SUM(points),0) total FROM participations');const[recent]=await pool.query('SELECT c.name campaign,e.name establishment,u.name customer,v.participation_points points,v.validated_at FROM visits v JOIN campaigns c ON c.id=v.campaign_id JOIN establishments e ON e.id=v.establishment_id JOIN users u ON u.id=v.user_id ORDER BY v.validated_at DESC LIMIT 10');res.json({totals:{campaigns:campaigns.total,activeCampaigns:activeCampaigns.total,users:users.total,establishments:establishments.total,visits:visits.total,points:points.total},recent})});
app.get('/api/admin/campaigns',auth,requireAdmin,async(_,res)=>{const[r]=await pool.query('SELECT c.*,COUNT(DISTINCT ce.establishment_id) establishment_count,COUNT(DISTINCT v.id) visit_count,COALESCE(SUM(p.points),0) points_total FROM campaigns c LEFT JOIN campaign_establishments ce ON ce.campaign_id=c.id AND ce.active=TRUE LEFT JOIN visits v ON v.campaign_id=c.id LEFT JOIN participations p ON p.campaign_id=c.id GROUP BY c.id ORDER BY c.start_date DESC,c.id DESC');res.json(r)});
app.post('/api/admin/campaigns',auth,requireAdmin,async(req,res)=>{const{name,slug,campaignType='TORTILLA',editionNumber,description,startDate,endDate,firstVisitPoints=2,repeatVisitPoints=1}=req.body;if(!name||!slug)return res.status(400).json({error:'Nombre y slug son obligatorios'});try{const[r]=await pool.query('INSERT INTO campaigns(name,slug,campaign_type,edition_number,description,start_date,end_date,first_visit_points,repeat_visit_points) VALUES(?,?,?,?,?,?,?,?,?)',[name.trim(),slug.trim(),campaignType,editionNumber||null,description||null,startDate||null,endDate||null,Number(firstVisitPoints),Number(repeatVisitPoints)]);res.status(201).json({id:r.insertId})}catch(e){res.status(e.code==='ER_DUP_ENTRY'?409:500).json({error:e.code==='ER_DUP_ENTRY'?'El slug ya existe':'No se pudo crear la campaña'})}});
app.get('/api/admin/establishments',auth,requireAdmin,async(_,res)=>{const[r]=await pool.query('SELECT e.*,COUNT(DISTINCT ce.campaign_id) campaign_count,COUNT(DISTINCT v.id) visit_count FROM establishments e LEFT JOIN campaign_establishments ce ON ce.establishment_id=e.id AND ce.active=TRUE LEFT JOIN visits v ON v.establishment_id=e.id GROUP BY e.id ORDER BY e.name');res.json(r)});
app.post('/api/admin/establishments',auth,requireAdmin,async(req,res)=>{if(!req.body.name)return res.status(400).json({error:'El nombre es obligatorio'});const[r]=await pool.query('INSERT INTO establishments(name,address) VALUES(?,?)',[req.body.name.trim(),req.body.address||null]);res.status(201).json({id:r.insertId})});
app.get('/api/admin/campaigns/:id/establishments',auth,requireAdmin,async(req,res)=>{const[r]=await pool.query('SELECT e.id,e.name,e.address,e.active establishment_active,COALESCE(ce.active,FALSE) assigned,COALESCE(ce.display_order,9999) display_order FROM establishments e LEFT JOIN campaign_establishments ce ON ce.establishment_id=e.id AND ce.campaign_id=? ORDER BY assigned DESC,display_order,e.name',[Number(req.params.id)]);res.json(r)});
app.post('/api/admin/campaigns/:id/establishments',auth,requireAdmin,async(req,res)=>{const cid=Number(req.params.id),eid=Number(req.body.establishmentId);const[a]=await pool.query('SELECT id FROM campaign_establishments WHERE campaign_id=? AND establishment_id=?',[cid,eid]);if(a.length){await pool.query('UPDATE campaign_establishments SET active=? WHERE id=?',[req.body.active!==false,a[0].id])}else{const[[m]]=await pool.query('SELECT COALESCE(MAX(display_order),0)+1 next_order FROM campaign_establishments WHERE campaign_id=?',[cid]);await pool.query('INSERT INTO campaign_establishments(campaign_id,establishment_id,display_order,active) VALUES(?,?,?,?)',[cid,eid,m.next_order,req.body.active!==false])}res.json({ok:true})});
app.get('/api/admin/campaigns/:id/prizes',auth,requireAdmin,async(req,res)=>{const[r]=await pool.query('SELECT * FROM prizes WHERE campaign_id=? ORDER BY id DESC',[Number(req.params.id)]);res.json(r)});
app.post('/api/admin/campaigns/:id/prizes',auth,requireAdmin,async(req,res)=>{if(!req.body.name)return res.status(400).json({error:'El nombre del premio es obligatorio'});const[r]=await pool.query('INSERT INTO prizes(campaign_id,name,description,quantity) VALUES(?,?,?,?)',[Number(req.params.id),req.body.name,req.body.description||null,Number(req.body.quantity||1)]);res.status(201).json({id:r.insertId})});
app.get('/api/admin/campaigns/:id/draws',auth,requireAdmin,async(req,res)=>{const[r]=await pool.query('SELECT d.*,COUNT(DISTINCT de.id) entries,COUNT(DISTINCT w.id) winners FROM draws d LEFT JOIN draw_entries de ON de.draw_id=d.id LEFT JOIN winners w ON w.draw_id=d.id WHERE d.campaign_id=? GROUP BY d.id ORDER BY d.id DESC',[Number(req.params.id)]);res.json(r)});
app.post('/api/admin/campaigns/:id/draws',auth,requireAdmin,async(req,res)=>{if(!req.body.name)return res.status(400).json({error:'Nombre del sorteo obligatorio'});const[r]=await pool.query('INSERT INTO draws(campaign_id,name,draw_date) VALUES(?,?,?)',[Number(req.params.id),req.body.name,req.body.drawDate||null]);res.status(201).json({id:r.insertId})});
app.get('/api/admin/campaigns/:id/participants',auth,requireAdmin,async(req,res)=>{const[r]=await pool.query('SELECT u.id,u.name,u.phone,COUNT(p.id) visits,COALESCE(SUM(p.points),0) points FROM users u JOIN participations p ON p.user_id=u.id AND p.campaign_id=? GROUP BY u.id,u.name,u.phone ORDER BY points DESC,u.name',[Number(req.params.id)]);res.json(r)});

app.listen(port,()=>console.log(`API http://localhost:${port}`));
